-- AlterTable
ALTER TABLE "Patient" ALTER COLUMN "name" DROP NOT NULL;
ALTER TABLE "Patient" ALTER COLUMN "dateOfBirth" DROP NOT NULL;
ALTER TABLE "Patient" ALTER COLUMN "phone" DROP NOT NULL;
ALTER TABLE "Patient" ALTER COLUMN "email" DROP NOT NULL;
ALTER TABLE "Patient" ALTER COLUMN "address" DROP NOT NULL;
ALTER TABLE "Patient" ALTER COLUMN "healthInsurance" DROP NOT NULL;
ALTER TABLE "Patient" ALTER COLUMN "clinicHistory" DROP NOT NULL;
